export const PENDING_SALESP_LIST_REQUEST = "PENDING_SALESP_LIST_REQUEST";
export const PENDING_SALESP_LIST_SUCCESS = "PENDING_SALESP_LIST_SUCCESS";
export const PENDING_SALESP_LIST_ERROR = "PENDING_SALESP_LIST_ERROR";

export const PENDING_SALESP_STATUS_REQUEST = "PENDING_SALESP_STATUS_REQUEST";
export const PENDING_SALESP_STATUS_SUCCESS = "PENDING_SALESP_STATUS_SUCCESS";
export const PENDING_SALESP_STATUS_ERROR = "PENDING_SALESP_STATUS_ERROR";

export const GET_STAFF_LIST_REQUEST = "GET_STAFF_LIST_REQUEST";
export const GET_STAFF_LIST_SUCCESS = "GET_STAFF_LIST_SUCCESS";
export const GET_STAFF_LIST_ERROR = "GET_STAFF_LIST_ERROR";

export const GET_ACTIVE_PROMOTERS_LIST_REQUEST =
  "GET_ACTIVE_PROMOTERS_LIST_REQUEST";
export const GET_ACTIVE_PROMOTERS_LIST_SUCCESS =
  "GET_ACTIVE_PROMOTERS_LIST_SUCCESS";
export const GET_ACTIVE_PROMOTERS_LIST_ERROR =
  "GET_ACTIVE_PROMOTERS_LIST_ERROR";

export const POST_STAFF_REQUEST = "POST_STAFF_REQUEST";
export const POST_STAFF_SUCCESS = "POST_STAFF_SUCCESS";
export const POST_STAFF_ERROR = "POST_STAFF_ERROR";

// export const PENDING_SALESP_STATUS_REQUEST = 'PENDING_SALESP_STATUS_REQUEST'
// export const PENDING_SALESP_STATUS_SUCCESS = 'PENDING_SALESP_STATUS_SUCCESS'
// export const PENDING_SALESP_STATUS_ERROR = 'PENDING_SALESP_STATUS_ERROR'

export const POST_PROMOTER_OUTLET_REQUEST = "POST_PROMOTER_OUTLET_REQUEST";
export const POST_PROMOTER_OUTLET_SUCCESS = "POST_PROMOTER_OUTLET_SUCCESS";
export const POST_PROMOTER_OUTLET_ERROR = "POST_PROMOTER_OUTLET_ERROR";

export const POST_MANAGER_STATE_REQUEST = "POST_MANAGER_STATE_REQUEST";
export const POST_MANAGER_STATE_SUCCESS = "POST_MANAGER_STATE_SUCCESS";
export const POST_MANAGER_STATE_ERROR = "POST_MANAGER_STATE_ERROR";
