export const UPLOAD_BULK_SALE_REQUEST = "UPLOAD_BULK_SALE_REQUEST";
export const UPLOAD_BULK_SALE_SUCCESS = "UPLOAD_BULK_SALE_SUCCESS";
export const UPLOAD_BULK_SALE_ERROR = "UPLOAD_BULK_SALE_ERROR";

export const GET_BULK_SALE_REQUEST = "GET_BULK_SALE_REQUEST";
export const GET_BULK_SALE_SUCCESS = "GET_BULK_SALE_SUCCESS";
export const GET_BULK_SALE_ERROR = "GET_BULK_SALE_ERROR";

export const DOWNLOAD_BULK_SALE_REQUEST = "DOWNLOAD_BULK_SALE_REQUEST";
export const DOWNLOAD_BULK_SALE_SUCCESS = "DOWNLOAD_BULK_SALE_SUCCESS";
export const DOWNLOAD_BULK_SALE_ERROR = "DOWNLOAD_BULK_SALE_ERROR";

export const UNKNOWN_SERIAL_REQUEST = "UNKNOWN_SERIAL_REQUEST";
export const UNKNOWN_SERIAL_SUCCESS = "UNKNOWN_SERIAL_SUCCESS";
export const UNKNOWN_SERIAL_ERROR = "UNKNOWN_SERIAL_ERROR";

export const GET_SALES_DATA_REQUEST = "GET_SALES_DATA_REQUEST";
export const GET_SALES_DATA_SUCCESS = "GET_SALES_DATA_SUCCESS";
export const GET_SALES_DATA_ERROR = "GET_SALES_DATA_ERROR";

export const UPDATE_SALES_DATA_REQUEST = "UPDATE_SALES_DATA_REQUEST";
export const UPDATE_SALES_DATA_SUCCESS = "UPDATE_SALES_DATA_SUCCESS";
export const UPDATE_SALES_DATA_ERROR = "UPDATE_SALES_DATA_ERROR";

export const DOWNLOAD_SALES_DATA_REQUEST = "DOWNLOAD_SALES_DATA_REQUEST";
export const DOWNLOAD_SALES_DATA_SUCCESS = "DOWNLOAD_SALES_DATA_SUCCESS";
export const DOWNLOAD_SALES_DATA_ERROR = "DOWNLOAD_SALES_DATA_ERROR";

export const CHECK_SERIAL_REQUEST = "CHECK_SERIAL_REQUEST";
export const CHECK_SERIAL_SUCCESS = "CHECK_SERIAL_SUCCESS";
export const CHECK_SERIAL_ERROR = "CHECK_SERIAL_ERROR";
