export const DOWNLOAD_PROMOTER_ATTENDANCE_REQUEST =
  "DOWNLOAD_PROMOTER_ATTENDANCE_REQUEST";
export const DOWNLOAD_PROMOTER_ATTENDANCE_SUCCESS =
  "DOWNLOAD_PROMOTER_ATTENDANCE_SUCCESS";
export const DOWNLOAD_PROMOTER_ATTENDANCE_ERROR =
  "DOWNLOAD_PROMOTER_ATTENDANCE_ERROR";

export const DOWNLOAD_INCENTIVE_PAYABLE_REQUEST =
  "DOWNLOAD_INCENTIVE_PAYABLE_REQUEST";
export const DOWNLOAD_INCENTIVE_PAYABLE_SUCCESS =
  "DOWNLOAD_INCENTIVE_PAYABLE_SUCCESS";
export const DOWNLOAD_INCENTIVE_PAYABLE_ERROR =
  "DOWNLOAD_INCENTIVE_PAYABLE_ERROR";

export const DOWNLOAD_NORMAL_INCENTIVE_ENTITLEMENT_REQUEST =
  "DOWNLOAD_NORMAL_INCENTIVE_ENTITLEMENT_REQUEST";
export const DOWNLOAD_NORMAL_INCENTIVE_ENTITLEMENT_SUCCESS =
  "DOWNLOAD_NORMAL_INCENTIVE_ENTITLEMENT_SUCCESS";
export const DOWNLOAD_NORMAL_INCENTIVE_ENTITLEMENT_ERROR =
  "DOWNLOAD_NORMAL_INCENTIVE_ENTITLEMENT_ERROR";

export const DOWNLOAD_BONUS_INCENTIVE_ENTITLEMENT_REQUEST =
  "DOWNLOAD_BONUS_INCENTIVE_ENTITLEMENT_REQUEST";
export const DOWNLOAD_BONUS_INCENTIVE_ENTITLEMENT_SUCCESS =
  "DOWNLOAD_BONUS_INCENTIVE_ENTITLEMENT_SUCCESS";
export const DOWNLOAD_BONUS_INCENTIVE_ENTITLEMENT_ERROR =
  "DOWNLOAD_BONUS_INCENTIVE_ENTITLEMENT_ERROR";

export const DOWNLOAD_TARGET_INCENTIVE_ENTITLEMENT_REQUEST =
  "DOWNLOAD_NORMAL_INCENTIVE_ENTITLEMENT_REQUEST";
export const DOWNLOAD_TARGET_INCENTIVE_ENTITLEMENT_SUCCESS =
  "DOWNLOAD_TARGET_INCENTIVE_ENTITLEMENT_SUCCESS";
export const DOWNLOAD_TARGET_INCENTIVE_ENTITLEMENT_ERROR =
  "DOWNLOAD_TARGET_INCENTIVE_ENTITLEMENT_ERROR";

export const DOWNLOAD_DEALER_INCENTIVE_ENTITLEMENT_REQUEST =
  "DOWNLOAD_DEALER_INCENTIVE_ENTITLEMENT_REQUEST";
export const DOWNLOAD_DEALER_INCENTIVE_ENTITLEMENT_SUCCESS =
  "DOWNLOAD_DEALER_INCENTIVE_ENTITLEMENT_SUCCESS";
export const DOWNLOAD_DEALER_INCENTIVE_ENTITLEMENT_ERROR =
  "DOWNLOAD_DEALER_INCENTIVE_ENTITLEMENT_ERROR";
