export const MOBILE_APP_SETTINGS_REQUEST = "MOBILE_APP_SETTINGS_REQUEST";
export const MOBILE_APP_SETTINGS_SUCCESS = "MOBILE_APP_SETTINGS_SUCCESS";
export const MOBILE_APP_SETTINGS_ERROR = "MOBILE_APP_SETTINGS_ERROR";

export const MOBILE_APP_SETTINGS_POST_REQUEST =
  "MOBILE_APP_SETTINGS_POST_REQUEST";
export const MOBILE_APP_SETTINGS_POST_SUCCESS =
  "MOBILE_APP_SETTINGS_POST_SUCCESS";
export const MOBILE_APP_SETTINGS_POST_ERROR = "MOBILE_APP_SETTINGS_POST_ERROR";
