export const OUTLET_PIC_LIST_REQUEST = "OUTLET_PIC_LIST_REQUEST";
export const OUTLET_PIC_LIST_SUCCESS = "OUTLET_PIC_LIST_SUCCESS";
export const OUTLET_PIC_LIST_ERROR = "OUTLET_PIC_LIST_ERROR";
export const OUTLET_PIC_REQUEST = "OUTLET_PIC_REQUEST";
export const OUTLET_PIC_SUCCESS = "OUTLET_PIC_SUCCESS";
export const OUTLET_PIC_ERROR = "OUTLET_PIC_ERROR";
export const OUTLET_PIC_POST_REQUEST = "OUTLET_PIC_POST_REQUEST";
export const OUTLET_PIC_POST_SUCCESS = "OUTLET_PIC_POST_SUCCESS";
export const OUTLET_PIC_POST_ERROR = "OUTLET_PIC_POST_ERROR";

export const OUTLET_LIST_REQUEST = "OUTLET_LIST_REQUEST";
export const OUTLET_LIST_SUCCESS = "OUTLET_LIST_SUCCESS";
export const OUTLET_LIST_ERROR = "OUTLET_LIST_ERROR";
export const OUTLET_WITH_PIC_LIST_REQUEST = "OUTLET_WITH_PIC_LIST_REQUEST";
export const OUTLET_WITH_PIC_LIST_SUCCESS = "OUTLET_WITH_PIC_LIST_SUCCESS";
export const OUTLET_WITH_PIC_LIST_ERROR = "OUTLET_WITH_PIC_LIST_ERROR";

export const OUTLET_REQUEST = "OUTLET_REQUEST";
export const OUTLET_SUCCESS = "OUTLET_SUCCESS";
export const OUTLET_ERROR = "OUTLET_ERROR";
export const OUTLET_POST_REQUEST = "OUTLET_POST_REQUEST";
export const OUTLET_POST_SUCCESS = "OUTLET_POST_SUCCESS";
export const OUTLET_POST_ERROR = "OUTLET_POST_ERROR";
export const OUTLET_BULK_UPLOAD_REQUEST = "OUTLET_BULK_UPLOAD_REQUEST";
export const OUTLET_BULK_UPLOAD_SUCCESS = "OUTLET_BULK_UPLOAD_SUCCESS";
export const OUTLET_BULK_UPLOAD_ERROR = "OUTLET_BULK_UPLOAD_ERROR";

export const DEALER_OUTLET_LIST_REQUEST = "DEALER_OUTLET_LIST_REQUEST";
export const DEALER_OUTLET_LIST_SUCCESS = "DEALER_OUTLET_LIST_SUCCESS";
export const DEALER_OUTLET_LIST_ERROR = "DEALER_OUTLET_LIST_ERROR";
