export const EXCLUSIVE_MTM_POST_REQUEST = "EXCLUSIVE_MTM_POST_REQUEST";
export const EXCLUSIVE_MTM_POST_SUCCESS = "EXCLUSIVE_MTM_POST_SUCCESS";
export const EXCLUSIVE_MTM_POST_ERROR = "EXCLUSIVE_MTM_POST_ERROR";

export const EXCLUSIVE_MTM_UPLOAD_REQUEST = "EXCLUSIVE_MTM_UPLOAD_REQUEST";
export const EXCLUSIVE_MTM_UPLOAD_SUCCESS = "EXCLUSIVE_MTM_UPLOAD_SUCCESS";
export const EXCLUSIVE_MTM_UPLOAD_ERROR = "EXCLUSIVE_MTM_UPLOAD_ERROR";
